In [1]:
import pandas as pd
import numpy as np
TRAINING_DATA_FILE = 'SpamData/02_Training/train-data.txt'
TEST_DATA_FILE = 'SpamData/02_Training/test-data.txt'

In [2]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, delimiter = ' ', dtype = int)
sparse_test_data = np.loadtxt(TEST_DATA_FILE, delimiter = ' ', dtype = int)

In [3]:
type(sparse_train_data)

numpy.ndarray

In [4]:
sparse_train_data

array([[   0,    2,    1,    1],
       [   0,    3,    1,    2],
       [   0,    4,    1,    1],
       ...,
       [5797, 2249,    0,    1],
       [5797, 2347,    0,    1],
       [5797, 2374,    0,    1]])

In [5]:
sparse_train_data.shape

(259350, 4)

In [6]:
sparse_test_data.shape

(116879, 4)

In [7]:
np.unique(sparse_train_data[:, 0]).size

4014

In [8]:
np.unique(sparse_test_data[:, 0]).size

1725

In [9]:
VOCAB_SIZE = 2500

In [12]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx = 0, word_idx =1, cat_idx = 2, freq_idx = 3):
    
    column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
    doc_id_names = np.unique(sparse_matrix[:, 0])
    full_matrix = pd.DataFrame(index = doc_id_names, columns = column_names)
    full_matrix.fillna(value = 0, inplace = True)
    
    for i in range(sparse_matrix.shape[0]):
        doc_nr = sparse_matrix[i][doc_idx]
        word_id = sparse_matrix[i][word_idx]
        label = sparse_matrix[i][cat_idx]
        occurance = sparse_matrix[i][freq_idx]
        
        full_matrix.at[doc_nr, 'DOC_ID'] = doc_nr
        full_matrix.at[doc_nr, 'CATEGORY'] = label
        full_matrix.at[doc_nr, word_id] = occurance
    full_matrix.set_index('DOC_ID', inplace = True)
    return full_matrix

In [13]:
full_train_data = make_full_matrix(sparse_train_data, VOCAB_SIZE)
full_train_data

,CATEGORY,0,1,2,3,4,5,6,7,8,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
DOC_ID,,,,,,,,,,,,,,,,,,,,,
0,1,0,0,1,2,1,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0
1,1,7,1,2,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,6,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1,6,0,0,2,4,0,3,14,0,...,0,0,0,0,0,1,0,0,0,0
4,1,5,1,2,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5793,0,3,1,0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5794,0,2,2,0,1,0,0,2,1,0,...,0,0,0,0,0,0,0,0,0,0
5795,0,1,9,1,0,0,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
5796,0,1,1,1,0,0,1,2,0,0,...,0,0,0,0,0,0,0,0,0,0
5797,0,3,4,2,0,5,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
full_train_data.CATEGORY.size

4014

In [16]:
full_train_data.CATEGORY.sum()

1247

In [19]:
prob_spam = full_train_data.CATEGORY.sum()/full_train_data.CATEGORY.size
prob_spam

0.3106626806178376

In [22]:
full_train_features = full_train_data.loc[:, 0:]
full_train_features

,0,1,2,3,4,5,6,7,8,9,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
DOC_ID,,,,,,,,,,,,,,,,,,,,,
0,0,0,1,2,1,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,1,2,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,1,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,6,0,0,2,4,0,3,14,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,1,2,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5793,3,1,0,1,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5794,2,2,0,1,0,0,2,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5795,1,9,1,0,0,1,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
5796,1,1,1,0,0,1,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5797,3,4,2,0,5,0,3,0,0,4,...,0,0,0,0,0,0,0,0,0,0

In [23]:
email_lengths = full_train_features.sum(axis =1)
email_lengths

DOC_ID
0        87
1        53
2        40
3       183
4        43
       ...
5793     46
5794     30
5795    228
5796     57
5797    264
Length: 4014, dtype: int64

In [30]:
email_lengths.max()

6869

In [32]:
email_lengths.shape[0]

4014

In [33]:
total_wc = email_lengths.sum()
total_wc

429329

In [35]:
spam_lengths = email_lengths[full_train_data.CATEGORY ==1]
spam_lengths

DOC_ID
0        87
1        53
2        40
3       183
4        43
       ...
1885     45
1887     26
1889    115
1890     26
1895    162
Length: 1247, dtype: int64

In [36]:
ham_lengths = email_lengths[full_train_data.CATEGORY ==0]
ham_lengths

DOC_ID
1896     82
1898     41
1899     41
1900    112
1901     66
       ...
5793     46
5794     30
5795    228
5796     57
5797    264
Length: 2767, dtype: int64

In [38]:
nonspam_wc = ham_lengths.sum()
nonspam_wc

253045

In [39]:
spam_wc = spam_lengths.sum()
spam_wc

176284

In [41]:
spam_wc+nonspam_wc

429329

In [42]:
train_spam_token = full_train_features.loc[full_train_data.CATEGORY ==1]
train_spam_token

,0,1,2,3,4,5,6,7,8,9,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
DOC_ID,,,,,,,,,,,,,,,,,,,,,
0,0,0,1,2,1,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,1,2,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,1,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,6,0,0,2,4,0,3,14,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,1,2,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,1,0,0,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1887,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1889,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1890,2,0,0,0,1,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1895,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
train_spam_token.shape

(1247, 2500)

In [44]:
summed_spam_token = train_spam_token.sum(axis=0)+1
summed_spam_token

0       2180
1        935
2       1219
3       2021
4       1215
        ...
2495      28
2496      26
2497       2
2498      15
2499      22
Length: 2500, dtype: int64

In [45]:
prob_spam_token = summed_spam_token/(spam_wc+VOCAB_SIZE)
prob_spam_token

0       0.012193
1       0.005230
2       0.006818
3       0.011304
4       0.006796
          ...
2495    0.000157
2496    0.000145
2497    0.000011
2498    0.000084
2499    0.000123
Length: 2500, dtype: float64

In [51]:
round(prob_spam_token.sum(),2)

1.0

In [47]:
train_ham_tokens = full_train_features.loc[full_train_data.CATEGORY == 0]
summed_ham_tokens = train_ham_tokens.sum(axis=0) + 1 
summed_ham_tokens

0       5366
1       2597
2       2043
3        933
4       1646
        ...
2495      12
2496       4
2497      33
2498      14
2499       6
Length: 2500, dtype: int64

In [49]:
prob_ham_tokens = summed_ham_tokens/(nonspam_wc+VOCAB_SIZE)
prob_ham_tokens

0       0.020998
1       0.010163
2       0.007995
3       0.003651
4       0.006441
          ...
2495    0.000047
2496    0.000016
2497    0.000129
2498    0.000055
2499    0.000023
Length: 2500, dtype: float64

In [50]:
prob_ham_tokens.sum()

1.0

In [52]:
prob_token_all = full_train_features.sum(axis=0)/total_wc

In [53]:
prob_token_all

0       0.017572
1       0.008222
2       0.007593
3       0.006876
4       0.006659
          ...
2495    0.000089
2496    0.000065
2497    0.000077
2498    0.000063
2499    0.000061
Length: 2500, dtype: float64

In [54]:
prob_token_all.sum()

1.0

In [55]:
TOKEN_SPAM_PROB_FILE = 'SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'SpamData/03_Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = 'SpamData/03_Testing/prob-all-tokens.txt'

In [59]:
np.savetxt(TOKEN_SPAM_PROB_FILE, prob_spam_token)
np.savetxt(TOKEN_HAM_PROB_FILE, prob_ham_tokens)
np.savetxt(TOKEN_ALL_PROB_FILE,prob_token_all)

In [64]:
sparse_test_data[:]

array([[   8,    2,    1,    1],
       [   8,    3,    1,    4],
       [   8,    4,    1,    2],
       ...,
       [5792, 1668,    0,    1],
       [5792, 2078,    0,    1],
       [5792, 2178,    0,    1]])

In [65]:
sparse_test_data.shape

(116879, 4)

In [66]:
full_test_data = make_full_matrix(sparse_test_data, nr_words=VOCAB_SIZE)
full_test_data

,CATEGORY,0,1,2,3,4,5,6,7,8,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
DOC_ID,,,,,,,,,,,,,,,,,,,,,
8,1,0,0,1,4,2,1,2,4,1,...,0,0,0,0,0,0,0,0,0,0
12,1,6,1,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1,0,2,1,1,2,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0
17,1,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5782,0,0,0,0,0,0,5,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5785,0,2,1,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5788,0,5,5,2,2,1,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5790,0,0,4,0,2,4,3,3,1,4,...,0,0,0,0,0,0,0,0,0,0
5792,0,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [67]:
X_test=full_test_data.loc[:, full_test_data.columns != 'CATEGORY']
X_test

,0,1,2,3,4,5,6,7,8,9,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
DOC_ID,,,,,,,,,,,,,,,,,,,,,
8,0,0,1,4,2,1,2,4,1,2,...,0,0,0,0,0,0,0,0,0,0
12,6,1,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,2,1,1,2,0,0,3,0,4,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5782,0,0,0,0,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5785,2,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5788,5,5,2,2,1,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5790,0,4,0,2,4,3,3,1,4,3,...,0,0,0,0,0,0,0,0,0,0
5792,1,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
X_test.shape

(1725, 2500)

In [69]:
full_test_data.shape

(1725, 2501)

In [70]:
y_test =full_test_data.CATEGORY

In [73]:
y_test.shape

(1725,)

In [74]:
TEST_FEATURE_MATRIX = 'SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE = 'SpamData/03_Testing/test-target.txt'

In [75]:
np.savetxt(TEST_FEATURE_MATRIX, X_test)
np.savetxt(TEST_TARGET_FILE, y_test)